mongodb_url = "mongodb://localhost:27017"
database = "ledger"
ic_url = "https://icp0.io"

# 代币配置列表
[[tokens]]
# 代币标识符 (用于在数据库中区分不同代币)
symbol = "VUSD"
# 代币名称
name = "VUSD"
# 代币canister_id
canister_id = "anbw7-hqaaa-aaaaj-az7ra-cai"
# 代币小数位
decimals = 6

# 可以添加更多代币配置
[[tokens]]
symbol = "LIKE"
name = "LIKE"
canister_id = "spdsf-5yaaa-aaaam-adcnq-cai"
decimals = 6

[[tokens]]
symbol = "WORM"
name = "WORM"
canister_id = "3j5nq-qqaaa-aaaam-acvrq-cai"

[[tokens]]
symbol = "NANAS"
name = "NANAS"
canister_id = "mwen2-oqaaa-aaaam-adaca-cai"

# 日志配置
[log]
# 日志级别: error, warn, info, debug, trace
level = "info"
# 日志文件路径
file = "logs/index-rs.log"
# 控制台日志级别 (可选，默认为warn)
console_level = "info"
# 是否启用文件日志
file_enabled = true
# 日志文件最大大小(MB)
max_size = 10
# 保留的历史日志文件数量
max_files = 5

# API服务器配置
[api_server]
# 是否启用API服务器
enabled = true
# API服务器端口
port = 6017
# 是否启用CORS支持
cors_enabled = true
