mongodb_url = "mongodb://localhost:27017"
database = "ledger"
ic_url = "https://icp0.io"
ledger_canister_id = "aiw2p-tyaaa-aaaam-aebyq-cai"

# 日志配置
[log]
# 日志级别: error, warn, info, debug, trace
level = "info"
# 日志文件路径
file = "logs/index-rs.log"
# 控制台日志级别 (可选，默认为warn)
console_level = "warn"
# 是否启用文件日志
file_enabled = true
# 日志文件最大大小(MB)
max_size = 10
# 保留的历史日志文件数量
max_files = 5
